---
dependencies:
  - { role: common }

galaxy_info:
  author: roadhouse
  description: Installs and configures Golang
  license: MIT
  min_ansible_version: '2.9'
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - development
    - golang
