---
- name:  Install autorandr
  apt:
    name: autorandr
    state: present
  become: true
  tags: autorandr

- name: Link autorandr config directory
  include_tasks: ../../common/tasks/includes/link_dotfiles.yml
  vars:
    config_dir: true
    role_name: autorandr
