---
- name: Add Golang backports PPA (Debian)
  include_tasks: ../../common/tasks/includes/add_repository.yml
  vars:
    role_name: golang
    repo_line: ppa:longsleep/golang-backports

- name: Install Golang {{ golang_version }} (Debian)
  include_tasks: ../../common/tasks/includes/install_packages.yml
  vars:
    package_name: "golang-{{ golang_version }}"
    role_name: golang
