---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  # Ansible-lint temporarily disabled
  # - repo: https://github.com/ansible-community/ansible-lint
  #   rev: v6.14.3
  #   hooks:
  #     - id: ansible-lint
  #       files: \.(yaml|yml)$

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.29.0
    hooks:
      - id: yamllint
        args: [-c=.yamllint]
