---
- name: Link atuin config directory
  include_tasks: ../../common/tasks/includes/link_dotfiles.yml
  vars:
    config_dir: true
    role_name: atuin

- name: Check if atuin is already installed
  command: which atuin
  register: atuin_check
  changed_when: false
  failed_when: false
  check_mode: false
  tags: atuin

- name: Include atuin installation tasks
  include_tasks: install.yml
  when: atuin_check.rc != 0
  tags: atuin
