---
- name:  Add Nushell GPG key (Debian)
  apt_key:
    url: https://apt.fury.io/nushell/gpg.key
    keyring: /etc/apt/trusted.gpg.d/fury-nushell.gpg
    state: present
  become: true
  tags: nushell

- name: Add Nushell repository (Debian)
  include_tasks: ../../common/tasks/includes/add_repository.yml
  vars:
    role_name: nushell
    repo_url: https://apt.fury.io/nushell/
    repo_key_url: "{{ repo_url }}gpg.key"
    repo_line: "deb {{ repo_url }} /"
    repo_filename: fury
    repo_key_options:
      keyring: /etc/apt/trusted.gpg.d/fury-nushell.gpg

- name: Install nushell (Debian)
  include_tasks: ../../common/tasks/includes/install_packages.yml
  vars:
    role_name: nushell
