---
# Include OS-specific tasks
- name:  Link nushell config files
  include_tasks: ../../common/tasks/includes/link_dotfiles.yml
  vars:
    dotfiles:
      - { src: 'config', dest: '.config/nushell' }
    role_name: nushell

- name: Include OS-specific tasks for Debian
  include_tasks: debian.yml
  when: ansible_facts['os_family'] == "Debian"

- name: Include OS-specific tasks for macOS
  include_tasks: darwin.yml
  when: ansible_facts['os_family'] == "Darwin"
