---
# Include OS-specific tasks
- name:  Link nushell config files
  include_tasks: ../../common/tasks/includes/link_dotfiles.yml
  vars:
    dotfiles:
      - { src: 'config', dest: '.config/nushell' }
    role_name: nushell

- name: Include OS-specific tasks
  include_tasks: "{{ ansible_facts['os_family'] | lower }}.yml"
