---
- name:  Add Nushell GPG key (Debian)
  apt_key:
    url: https://apt.fury.io/nushell/gpg.key
    keyring: /etc/apt/trusted.gpg.d/fury-nushell.gpg
    state: present
  become: true
  tags: nushell

- name:  Add Nushell repository (Debian)
  apt_repository:
    repo: deb https://apt.fury.io/nushell/ /
    state: present
    filename: fury
  become: true
  tags: nushell

- name:  Install nushell (Debian)
  package:
    name: nushell
    state: present
    update_cache: yes
  become: true
  tags: nushell
