---
# Include OS-specific tasks
- name: Include OS-specific tasks
  include_tasks: "{{ os_task_file }}"

- name:  Link zsh dotfiles
  include_tasks: ../../common/tasks/includes/link_dotfiles.yml
  vars:
    dotfiles:
      - { src: 'zshrc', dest: '.zshrc' }
    role_name: zsh
  tags: [zsh, config]
