---
- name: Install i3 and related packages
  include_tasks: ../../common/tasks/includes/install_packages.yml
  vars:
    package_names:
      - i3
      - i3blocks
      - i3lock
      - i3status
    role_name: i3

- name: Link i3 config directory
  include_tasks: ../../common/tasks/includes/link_dotfiles.yml
  vars:
    config_dir: true
    role_name: i3

- name: Link i3blocks config directory
  file:
    src: "{{ role_path }}/files/config/i3blocks"
    dest: "{{ lookup('env', 'HOME') }}/.config/i3blocks"
    state: link
    force: no
  tags: [i3, i3blocks, config]
