---
# Reusable task for including role-specific verification tasks
# Usage: include_tasks: includes/verify_role.yml role_name=golang

- name: Include {{ role_name }} role variables
  include_vars:
    file: "{{ playbook_dir }}/../../roles/{{ role_name }}/defaults/main.yml"
  when: role_name in converge_content['content'] | b64decode

- name: Include {{ role_name }} verification tasks
  include_tasks: "{{ playbook_dir }}/../../roles/{{ role_name }}/molecule/verify.yml"
  when:
    - role_name in converge_content['content'] | b64decode
    - lookup('first_found',
        [playbook_dir + '/../../roles/' + role_name + '/molecule/verify.yml'],
        errors='ignore'
      ) != ''
