---
- name: Include OS-specific tasks for {{ os_name }}
  include_tasks: "{{ os_task_file }}"

- name:  Link git dotfiles
  include_tasks: ../../common/tasks/includes/link_dotfiles.yml
  vars:
    dotfiles:
      - { src: 'gitconfig', dest: '.gitconfig' }
