---
- name:  Ensure curl is present
  apt:
    name: curl
    state: present
  become: true
  tags: k3s

- name: 🚀 Download k3s installer
  get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s-installer.sh
    mode: '0755'
  register: k3s_download
  tags: k3s

- name: 🚀 Install k3s
  command: sh -
  args:
    stdin: "{{ lookup('file', '/tmp/k3s-installer.sh') }}"
    creates: /usr/local/bin/k3s
  become: true
  tags: k3s
