---
- name: Personal Notebook Setup
  hosts: localhost
  become: true
  roles:
    # Core system
    - { role: common, tags: [common, base] }

    # Base components with no dependencies
    - { role: git, tags: [git, dev, base] }
    - { role: xorg, tags: [xorg, desktop] }
    - { role: zsh, tags: [zsh, base] }
    - { role: nushell, tags: [nushell, shell] }
    - { role: tmux, tags: [tmux, base] }
    - { role: touchpad, tags: [touchpad, notebook] }

    # Development tools
    - { role: nvim, tags: [nvim, base] }
    - { role: ruby, tags: [ruby, dev] }
    - { role: golang, tags: [go, dev] }

    # Shell enhancements
    - { role: starship, tags: [starship, base] }
    - { role: atuin, tags: [atuin, base] }

    # Desktop environment
    - { role: i3, tags: [i3, desktop] }
    - { role: autorandr, tags: [autorandr, desktop] }
    - { role: alacritty, tags: [alacritty, desktop] }
    - { role: rofi, tags: [rofi, desktop] }

    # Infrastructure
    - { role: k3s, tags: [k3s, infra] }
