---
- name: Test Role Integration
  hosts: localhost
  connection: local
  become: false
  gather_facts: true
  vars_files:
    - ../vars/test_config.yml
  vars:
    # Set test directory for role integration tests
    test_dir: "{{ test_base_dir }}/role_integration"
    test_type: "role_integration"
    code_dir: "{{ test_dir }}/code"
  tasks:
    - name: Create test directory
      file:
        path: "{{ test_dir }}"
        state: directory
        mode: '0755'

    - name: Display test information
      debug:
        msg: "Testing role integration in {{ test_dir }}"

    # Test common role
    - name: 📂 Test common role - directory creation
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ test_dir }}/.config"
        - "{{ code_dir }}"
      register: common_dir_result
      failed_when: false
      tags: common

    - name: Report common role status
      debug:
        msg: "Common role directory creation {{ 'succeeded' if common_dir_result is succeeded else 'failed' }}"
      tags: common

    # Test Git role
    - name: 🔗 Test Git role - dotfiles linking
      file:
        src: "{{ repo_root }}/ansible/roles/git/files/gitconfig"
        dest: "{{ test_dir }}/.gitconfig"
        state: link
        force: no
      register: git_link_result
      failed_when: false
      tags: git

    - name: Report Git role status
      debug:
        msg: "Git role dotfiles linking {{ 'succeeded' if git_link_result is succeeded else 'failed' }}"
      tags: git

    # Test Ruby role
    - name: 🔗 Test Ruby role - dotfiles linking
      file:
        src: "{{ repo_root }}/ansible/roles/ruby/files/{{ item }}"
        dest: "{{ test_dir }}/.{{ item }}"
        state: link
        force: no
      loop:
        - irbrc
        - pryrc
      register: ruby_link_result
      failed_when: false
      tags: ruby

    - name: Report Ruby role status
      debug:
        msg: "Ruby role dotfiles linking {{ 'succeeded' if ruby_link_result is succeeded else 'failed' }}"
      tags: ruby

    # Cleanup test directory
    - name: Clean up test directory
      file:
        path: "{{ test_dir }}"
        state: absent
      when: cleanup_test_dir | default(true)
