---
- name: Install rofi
  include_tasks: ../../common/tasks/includes/install_packages.yml
  vars:
    role_name: rofi

- name: Link rofi config directory
  include_tasks: ../../common/tasks/includes/link_dotfiles.yml
  vars:
    config_dir: true
    role_name: rofi
