---
- name: Include OS-specific variables
  include_vars: ../vars/debian.yml

- name: Add Ghostty repository (Debian)
  include_tasks: ../../common/tasks/includes/add_repository.yml
  vars:
    role_name: ghostty
    repo_url: "{{ ghostty_repo_base_url }}"
    repo_key_url: "{{ ghostty_repo_key_url }}"
    repo_line: "{{ ghostty_repo_line }}"

- name: Install Ghostty (Debian)
  include_tasks: ../../common/tasks/includes/install_packages.yml
  vars:
    role_name: ghostty
    update_cache: true
