---
- name: Add Ghostty repository (Debian)
  become: true
  apt_repository:
    repo: deb https://download.opensuse.org/repositories/home:clayrisser:bookworm/Debian_12/ /
    state: present
  tags: ghostty

- name: Add Ghostty repository signing key (Debian)
  become: true
  apt_key:
    url: https://download.opensuse.org/repositories/home:clayrisser:bookworm/Debian_12/Release.key
    state: present
  tags: ghostty

- name: Install Ghostty (Debian)
  become: true
  package:
    name: ghostty
    state: present
    update_cache: yes
  tags: ghostty
