---
# Include OS-specific tasks
- name: Include OS-specific tasks for Debian
  include_tasks: debian.yml
  when: ansible_facts['os_family'] == "Debian"

- name: Include OS-specific tasks for macOS
  include_tasks: darwin.yml
  when: ansible_facts['os_family'] == "Darwin"

- name:  Link git dotfiles
  include_tasks: ../../common/tasks/includes/link_dotfiles.yml
  vars:
    dotfiles:
      - { src: 'gitconfig', dest: '.gitconfig' }
    role_name: git
