---
# Include OS-specific tasks
- name: Include OS-specific tasks
  include_tasks: "{{ os_task_file }}"

- name: Link tmux config directory
  include_tasks: ../../common/tasks/includes/link_dotfiles.yml
  vars:
    config_dir: true
    role_name: tmux
