---
# Include OS-specific tasks
- name: Include OS-specific tasks
  include_tasks: "{{ ansible_facts['os_family'] | lower }}.yml"

- name: Link tmux config directory
  include_tasks: ../../common/tasks/includes/link_dotfiles.yml
  vars:
    config_dir: true
    role_name: tmux
