---
# Include OS-specific tasks
- name: Include OS-specific tasks for Debian
  include_tasks: debian.yml
  when: ansible_facts['os_family'] == "Debian"

- name: Include OS-specific tasks for macOS
  include_tasks: darwin.yml
  when: ansible_facts['os_family'] == "Darwin"

- name:  Link tmux config directory
  file:
    src: "{{ role_path }}/files/config"
    dest: "{{ lookup('env', 'HOME') }}/.config/tmux"
    state: link
    force: no
  tags: [tmux, config]
