#!/bin/bash

# Load RVM, if you are using it
[[ -s $HOME/.rvm/scripts/rvm ]] && source $HOME/.rvm/scripts/rvm

# Add rvm gems and nginx to the path
export PATH=$PATH:.:./script:/usr/local/sbin:/usr/local/bin

# Path to the bash it configuration
export BASH=$HOME/.bash-it

# Lock and Load a custom theme file
# location /.bash_it/themes/
export BASH_THEME='clean'

# Your place for hosting Git repos. I use this for private repos.
export GIT_HOSTING='git@git.domain.com'

# Set my editor and git editor
export EDITOR="/usr/bin/mate -w"
export GIT_EDITOR='/usr/bin/mate -w'

# set x86_64 flags
export CFLAGS="-arch x86_64 -O2"
export ARCHFLAGS="-arch x86_64"

# new paths to cd completion
export CDPATH=.:~:~/code:~/code/ruby:~/code/github/

# correct the typos in the cd command automatically
shopt -s cdspell

# Bash will now check the size every time it displays a promp
shopt -s checkwinsize

# Don't check mail when opening terminal.
unset MAILCHECK

# Set this to the command you use for todo.txt-cli
export TODO="t"

# Set store directory for handmade commandline history tool
export hchtstoredir="$HOME/.hcht"

# Load Bash It
source $BASH/bash_it.sh

#FIXME put this on correct dir
complete -C ~/code/dotfiles/autocomplete/capistrano_autocomplete -o default capistrano

PS1='\n\[\033[1;33m\][$(~/.rvm/bin/rvm-prompt v g)]\[\033[0m\] \w$(__git_ps1 " \[\033[1;32m\](%s)\[\033[0m\]")\n\$ '
