_load_scripts_from() {
  for file in $(ls -d "$1/"*); do source $file; done
}

setopt appendhistory
setopt autocd
bindkey -v
bindkey "^R" history-incremental-pattern-search-backward

CDPATH=.:~/code/
CLICOLOR="auto"
EDITOR=nvim
GREP_COLOR="4;33"
GREP_OPTIONS="--color=auto"
HISTCONTROL=ignoreboth
HISTFILE=~/.cache/zshhistory
HISTSIZE=10000
PATH=$HOME/.local/bin:/usr/local/bin:/snap/bin/:$HOME/go/bin:$PATH
SAVEHIST=10000
TERM='xterm-256color'

source ~/code/zsh-snap/znap.zsh
znap prompt romkatv/powerlevel10k

source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/code/dotfiles/zsh/p10k.zsh
[ -f ~/code/dotfiles/zsh/machines/$(hostname).sh ] && source ~/code/dotfiles/zsh/machines/$(hostname).sh

_load_scripts_from ~/code/dotfiles/zsh/lang
