---
- name:  Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install base packages
  apt:
    name:
      - bat
      - curl
      - fzf
      - jq
      - software-properties-common
      - xclip
      - gpg-agent
      - dirmngr
    state: present
