---
# Include OS-specific tasks
- name: Include OS-specific package installation
  include_tasks: "{{ os_task_file }}"

- name:  Ensure ~/.config exists
  file:
    path: "{{ lookup('env', 'HOME') }}/.config"
    state: directory
    mode: '0755'
