---
- name: Converge
  hosts: all
  become: true
  vars_files:
    - ../../defaults/main.yml

  tasks:
    # Test the role
    - name: Include golang role
      include_role:
        name: "../../../golang"

    # Add symlink for easier testing
    - name: Create symlink for go binary
      file:
        src: "{{ golang_bin_path }}/go"
        dest: /usr/bin/go
        state: link
      when: ansible_check_mode is not defined or not ansible_check_mode
