---
- name: Converge
  hosts: all
  become: true
  vars_files:
    - ../../defaults/main.yml
  vars:
    code_dir: /root/code  # Required by common role
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      changed_when: false

    - name: Install required packages
      apt:
        name:
          - software-properties-common
          - apt-transport-https
          - ca-certificates
          - dirmngr
          - gnupg
        state: present
      changed_when: false

  tasks:
    # Include the role for testing
    - name: Include golang role
      include_role:
        name: "../../../golang"

    # Add symlink for easier testing
    - name: Create symlink for go binary
      file:
        src: "{{ golang_bin_path }}/go"
        dest: /usr/bin/go
        state: link
      when: ansible_check_mode is not defined or not ansible_check_mode
