---
- name: Verify
  hosts: all
  vars_files:
    - ../../defaults/main.yml
  tasks:
    - name: Check if specific Go path exists
      stat:
        path: "{{ golang_bin_path }}/go"
      register: go_specific_path
      changed_when: false

    - name: Check if golang is installed (specific path)
      command: "{{ golang_bin_path }}/go version"
      register: go_version_specific
      changed_when: false
      when: go_specific_path.stat.exists

    - name: Check if golang is installed (general path)
      command: which go
      register: go_path
      changed_when: false
      failed_when: not go_specific_path.stat.exists and go_path.rc != 0
      when: not go_specific_path.stat.exists

    - name: Check golang version (general path)
      command: go version
      register: go_version_general
      changed_when: false
      when: not go_specific_path.stat.exists

    - name: Set go version fact
      set_fact:
        go_version_stdout: "{{ go_version_specific.stdout | default(go_version_general.stdout | default('')) }}"

    - name: Assert golang version
      assert:
        that:
          - "'go1.24' in go_version_stdout"
        fail_msg: "Unexpected golang version: {{ go_version_stdout }}"
