---
- name: Verify
  hosts: all
  vars_files:
    - ../../defaults/main.yml
  tasks:
    - name: Check if Go binary exists
      stat:
        path: "{{ golang_bin_path }}/go"
      register: go_binary
      changed_when: false

    - name: Verify Go is installed
      assert:
        that: go_binary.stat.exists
        fail_msg: "Go binary not found at {{ golang_bin_path }}/go"

    - name: Check Go version
      command: "{{ golang_bin_path }}/go version"
      register: go_version
      changed_when: false

    - name: Verify correct Go version
      assert:
        that: "'go{{ golang_version }}' in go_version.stdout"
        fail_msg: "Unexpected Go version: {{ go_version.stdout }}"
        success_msg: "Go {{ golang_version }} is correctly installed"
