---
- name: Include OS-specific tasks for {{ os_name }}
  include_tasks: "{{ os_task_file }}"

- name: Link Neovim config directory
  include_tasks: ../../common/tasks/includes/link_dotfiles.yml
  vars:
    config_dir: true
    role_name: nvim
